<?php

namespace ContainerXoxz4RP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordChangeFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PasswordChangeForm' shared autowired service.
     *
     * @return \App\Form\PasswordChangeForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PasswordChangeForm.php';

        return $container->privates['App\\Form\\PasswordChangeForm'] = new \App\Form\PasswordChangeForm();
    }
}
