<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoxz4RP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoxz4RP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXoxz4RP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXoxz4RP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXoxz4RP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xoxz4RP',
    'container.build_id' => '81500f29',
    'container.build_time' => 1624286529,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoxz4RP');
